name: seahax-planner
region: sfo
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
# features:
# - buildpack-stack=ubuntu-22

services:
  - name: seahax-planner
    image:
      deploy_on_push:
        enabled: true
      registry_type: DOCR
      repository: seahax-planner
      tag: latest
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb

ingress:
  rules:
    - component:
        name: seahax-planner
      match:
        path:
          prefix: /
