name: seahax-planner
region: sfo
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

services:
  - name: seahax-planner
    image:
      registry_type: DOCR
      repository: seahax-planner
      tag: latest
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb

ingress:
  rules:
    - component:
        name: seahax-planner
      match:
        path:
          prefix: /
