name: Common Workflow Setup
description: Setup tools and other prerequisites for workflows.

inputs:
  mise:
    description: "Whether to setup Mise."
    required: true

  docker:
    description: "Whether to setup Docker."
    required: true
  docker-registry:
    description: "Docker registry to login to."
    required: false
    default: ""
  docker-username:
    description: "Docker registry username."
    required: false
    default: ""
  docker-password:
    description: "Docker registry password."
    required: false
    default: ""

  npm-token:
    description: "NPM token for authentication."
    required: false
    default: ""
  npm-registry:
    description: "NPM registry URL."
    required: false
    default: "registry.npmjs.org"

  aws-profile:
    description: "AWS CLI profile name."
    required: false
    default: "default"
  aws-access-key-id:
    description: "AWS Access Key ID."
    required: false
    default: ""
  aws-secret-access-key:
    description: "AWS Secret Access Key."
    required: false
    default: ""
  aws-region:
    description: "AWS Region."
    required: false
    default: "us-east-1"

  restore:
    description: "Command to restore dependencies."
    required: false
  restore-shell:
    description: "Shell to use for the restore command."
    required: false
    default: "bash"

runs:
  using: composite
  steps:
    - name: Setup Mise
      if: inputs.mise == 'true'
      uses: jdx/mise-action@v2

    - name: Setup Docker
      if: inputs.docker == 'true'
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Setup NPM Auth
      if: inputs.npm-token != '' && inputs.npm-registry != ''
      shell: bash
      run: npm config set -L user "//${{ inputs.npm-registry }}/:_authToken" "${{ inputs.npm-token}}"

    - name: Setup AWS Auth
      if: inputs.aws-access-key-id != '' && inputs.aws-secret-access-key != ''
      shell: bash
      run: |
        aws configure --profile "${{ inputs.aws-profile }}" set aws_access_key_id "${{ inputs.aws-access-key-id }}"
        aws configure --profile "${{ inputs.aws-profile }}" set aws_secret_access_key "${{ inputs.aws-secret-access-key }}"
        aws configure --profile "${{ inputs.aws-profile }}" set region "${{ inputs.aws-region }}"

    - name: Setup Dependencies
      if: inputs.restore != ''
      shell: ${{ inputs.restore-shell }}
      run: ${{ inputs.restore }}
