packages:
  - packages/*
  - unreleased/*
  - templates/*
catalog:
  "@types/eslint": "^9.6.1"
  "eslint": "^9.17.0"
  "typescript": "^5.7.2"
  "vite": "^6.0.3"
  "vitest": "^3.0.5"
  "@vitest/coverage-v8": "^3.0.5"
