name: Cleanup Workflow Runs
description: Delete old workflow runs.

inputs:
  expire_days:
    description: "Number of days to keep workflow runs."
    default: "7"
  github_token:
    description: "Authentication token."
    default: ${{ github.token }}
  dry_run:
    description: "Dry run mode."
    default: "false"

runs:
  using: composite
  steps:
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: install
      shell: bash
      run: npm ci
      working-directory: ${{ github.action_path }}
    - name: cleanup
      shell: bash
      run: node action.ts
      working-directory: ${{ github.action_path }}
      env:
        EXPIRE_DAYS: ${{ inputs.expire_days }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        DRY_RUN: ${{ inputs.dry_run }}

branding:
  icon: "delete"
  color: "red"
