name: Delete Workflow Runs
description: Delete old workflow runs as an action in the workflow.

inputs:
  expire_days:
    description: "Number of days to keep workflow runs."
    default: "7"
  github_token:
    description: "Authentication token."
    default: ${{ github.token }}
  dry_run:
    description: "Dry run mode."
    default: "false"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - shell: bash
      run: npm ci
      working-directory: ${{ github.action_path }}
    - shell: bash
      run: npx tsx src/index.ts
      env:
        EXPIRE_DAYS: ${{ inputs.expire_days }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        DRY_RUN: ${{ inputs.dry_run }}
      working-directory: ${{ github.action_path }}

branding:
  icon: "delete"
  color: "red"
