${{vars}}:
  - key: app-pepper
    type: string

name: seahax
region: sfo
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

databases:
  - name: db
    cluster_name: seahax-db
    engine: MONGODB
    version: "8"
    production: true

services:
  - name: app
    image:
      registry_type: DOCR
      repository: seahax
      tag: latest
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: APP_ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: APP_ORIGIN
        scope: RUN_TIME
        value: https://seahax.com
      - key: APP_DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: APP_PEPPER
        scope: RUN_TIME
        value: ${{vars.app-pepper}}
        type: SECRET
    health_check:
      http_path: /_health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

ingress:
  rules:
    - component:
        name: app
      match:
        path:
          prefix: /

domains:
  - domain: seahax.com
    type: PRIMARY
    wildcard: true
