name: seahax
region: sfo
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

databases:
  - name: db
    cluster_name: seahax-db
    engine: MONGODB
    version: "8"
    production: true
  - name: cache
    cluster_name: seahax-cache
    engine: VALKEY
    version: "8"
    production: true

services:
  - name: app
    image:
      registry_type: DOCR
      registry: seahax
      repository: app
      tag: latest
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: APP_ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: APP_ORIGIN
        scope: RUN_TIME
        value: https://seahax.com
      - key: APP_MONGODB_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: APP_SENTRY_DSN
        scope: RUN_TIME
        value: https://8bccefc6c967115a3f7f41cb478fa2fd@o4509086879973376.ingest.us.sentry.io/4509086892949504
      - key: APP_SMTP_USERNAME
        scope: RUN_TIME
        value: noreply@seahax.com
      - key: APP_SMTP_SERVER
        scope: RUN_TIME
        value: smtp.protonmail.ch
      - key: APP_SMTP_PORT
        scope: RUN_TIME
        value: "587"
      - key: APP_SMTP_TOKEN
        scope: RUN_TIME
        value: EV[1:1bJle5sFdd3bHMppbla0YKMbT96VVb35:v9Dj4RZSSnwLYDKm/x/SXfCgk6K3dPOtPFbDLNdDaIU=]
        type: SECRET
    health_check:
      http_path: /_health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

ingress:
  rules:
    - component:
        name: app
      match:
        path:
          prefix: /

domains:
  - domain: seahax.com
    type: PRIMARY
    wildcard: true
