name: seahax
region: sfo
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

databases:
  - name: db
    cluster_name: seahax-data
    engine: MONGODB
    version: "8"
    production: true

services:
  - name: seahax
    image:
      registry_type: DOCR
      repository: app-seahax-backend
      tag: latest
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: CA_CERT
        scope: RUN_TIME
        value: ${db.CA_CERT}
    health_check:
      http_path: /_health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

ingress:
  rules:
    - component:
        name: seahax
      match:
        path:
          prefix: /

domains:
  - domain: seahax.com
    type: PRIMARY
    wildcard: true
