on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - apps/planner/**

env:
  APP_NAME: "seahax-planner"
  APP_PATH: "apps/planner"

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Setup
        run: ./.github/workflows/setup.sh
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: |
          set -e
          npx lerna --scope="$APP_NAME" run build
          npx lerna --scope="$APP_NAME" run build:docker -- -t "registry.digitalocean.com/seahax/${APP_NAME}:latest"
      - name: Check
        run: npx lerna --scope="$APP_NAME" run check
      - name: Push
        run: |
          set -e
          docker login registry.digitalocean.com -u "${{ secrets.DIGITALOCEAN_USERNAME }}" -p "${{ secrets.DIGITALOCEAN_TOKEN }}"
          docker push "registry.digitalocean.com/seahax/${APP_NAME}:latest"
      - name: Deploy
        uses: digitalocean/app_action/deploy@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
          project_id: ${{ secrets.DIGITALOCEAN_PROJECT }}
          app_spec_location: "${APP_PATH}/app.yaml"
