on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths-ignore:
      - ".devcontainer/**"
      - "templates/**"
      - "unreleased/**"
concurrency:
  group: ${{ github.workflow }}
env:
  TERM: xterm
  NO_COLOR: 1
  FORCE_COLOR: ''
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Setup
        working-directory: ./.github/workflows
        run: ./setup.sh
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Check
        run: pnpm check
      - name: Publish
        run: npx lerna --no-private publish from-package --no-git-tag-version --no-push --yes
