on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths-ignore:
      - '.devcontainer/**'
      - 'templates/**'
      - 'unreleased/**'
concurrency:
  group: ${{ github.workflow }}
env:
  TERM: xterm-256color
  FORCE_COLOR: 1
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: asdf-vm/actions/install@v3
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm check
      - run: npx lerna --no-private publish from-package --no-git-tag-version --no-push --yes
