on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths-ignore:
      - ".devcontainer/**"
      - "templates/**"
      - "unreleased/**"
concurrency:
  group: ${{ github.workflow }}
env:
  NODE_OPTIONS: --no-deprecation
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Setup
        run: ./.github/workflows/setup.sh
      - run: cat "$HOME/.npmrc"
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Check
        run: pnpm check
      - name: Publish
        run: |
          cat "$HOME/.npmrc"
          npx lerna --no-private publish from-package --no-git-tag-version --no-push --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
