name: Publish
run-name: ${{ github.workflow }}

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths-ignore:
      - ".devcontainer/**"
      - "apps/**"
      - "unreleased/**"
      - "templates/**"

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup
        run: ./.github/workflows/setup.sh

      - name: Restore
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Publish
        run: npx lerna --no-private publish from-package --no-git-tag-version --no-push --yes

  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cleanup
        uses: ./.github/actions/cleanup
